global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3001']

  - job_name: 'appointment-service'
    static_configs:
      - targets: ['appointment-service:3002']

  - job_name: 'provider-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['provider-service:3003']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
        replacement: 'provider-service:3003'

  - job_name: 'docker'
    static_configs:
      - targets: ['docker.for.mac.host.internal:9323']
    metrics_path: /metrics
    
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
