apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: api-gateway
    app.kubernetes.io/component: api-gateway
data:
  NODE_ENV: production
  LOG_LEVEL: info
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  # Add other non-sensitive configuration here
