apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "common.names.namespace" . | quote }}
  labels:
    app.kubernetes.io/name: {{ include "common.names.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: healthcare-appointment-system
