apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
type: Opaque
data:
  # These values should be base64 encoded
  # Example: echo -n "your-secret" | base64
  ADMIN_API_KEY: {{ required "ADMIN_API_KEY is required" .Values.secrets.adminApiKey | b64enc | quote }}
  USER_API_KEY: {{ required "USER_API_KEY is required" .Values.secrets.userApiKey | b64enc | quote }}
  JWT_SECRET: {{ required "JWT_SECRET is required" .Values.secrets.jwtSecret | b64enc | quote }}
