image:
  repository: ghcr.io/adityatagat/healthcare-appointment-system/api-gateway
  # This will be set by CI/CD pipeline to the GitHub SHA
  tag: ""

replicaCount: 2

color: blue

ingress:
  enabled: true
  host: api.yourdomain.com
  tls: true
  clusterIssuer: "letsencrypt-prod"

secrets:
  adminApiKey: ""
  userApiKey: ""
  jwtSecret: ""
