name: PR Checks

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Get npm cache directory
      id: npm-cache-dir
      working-directory: ./api-gateway
      run: |
        echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
    
    - name: Cache node modules
      uses: actions/cache@v3
      id: npm-cache
      with:
        path: |
          ~/.npm
          ./api-gateway/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'
        cache: 'npm'
        cache-dependency-path: 'api-gateway/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./api-gateway
      run: |
        # Create package-lock.json if it doesn't exist
        if [ ! -f package-lock.json ]; then
          npm install --package-lock-only
        fi
        npm ci
        
    - name: Run linting
      working-directory: ./api-gateway
      run: npm run lint || echo "Linting failed but continuing with tests"
      continue-on-error: true
      
    - name: Run tests
      working-directory: ./api-gateway
      env:
        NODE_ENV: test
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        CI: true
      run: |
        npm test -- --coverage --passWithNoTests
        
    - name: Upload test coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./api-gateway/coverage/lcov.info
        fail_ci_if_error: false

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Run npm audit
      working-directory: ./api-gateway
      run: npm audit --production
      
    - name: Run dependency-check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'api-gateway'
        path: './api-gateway'
        format: 'HTML'
        args: '--failOnCVSS 7'
